name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4            
    - name: Build the Docker image
      run: docker build --build-arg GITHUB_TOKEN=${{ secrets.PAT }} . --file Dockerfile --tag cloudxr-dev-env:latest
    # Run the command inside the Docker container to create the APK
    - name: Build APK
      run: docker run --name my-container -w /CloudXR-SDK_4_0_0/Client/Sample/Android/OculusVR cloudxr-dev-env:latest bash -c "./gradlew build"
    - name: Locate APK
      run: docker run --name my-container2 cloudxr-dev-env:latest bash -c "find /CloudXR-SDK_4_0_0/Client/Sample/Android/OculusVR/ -name '*.apk'"



