name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Use a GitHub token to authenticate and download the release asset
    - name: Download release asset with authentication
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token in Actions
      run: |
        curl -L -o CloudXR-SDK_4_0_0.zip -H "Authorization: token $GITHUB_TOKEN" https://github.com/peted70/CloudXR-Clients/releases/download/SDK_4.0.0/CloudXR-SDK_4_0_0.zip
    
       # Check if the download was successful and verify the file size
    - name: Verify download
      run: |
        if [ ! -f "CloudXR-SDK_4_0_0.zip" ]; then 
          echo "Download failed"; 
          exit 1; 
        fi
        
        FILE_SIZE=$(stat -c%s "CloudXR-SDK_4_0_0.zip")
        
        if [ "$FILE_SIZE" -le 100 ]; then 
          echo "Downloaded file is too small. Contents of the file:";
          cat CloudXR-SDK_4_0_0.zip;
          exit 1; 
        fi
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
